### ISSUE TITLE
避難所の数を表示したい

### ISSUE THREAD

**Issue by ShogoHirasawa** [furuhashilab/UNVT_for_Tokyo-to#8]

**Comment by ShogoHirasawa** [comment]
## 現状
<img width="1305" alt="スクリーンショット 2022-06-14 21 17 50" src="https://user-images.githubusercontent.com/29940264/173575477-330f44ef-f6da-4523-8744-06b40bbd96d3.png">

## 理想形
<img width="676" alt="スクリーンショット 2022-06-14 21 19 55" src="https://user-images.githubusercontent.com/29940264/173575607-74f4404c-82d9-4ad9-b32c-195b58a4bd08.png">
https://maplibre.org/maplibre-gl-js-docs/example/cluster/

## consoleのエラー
```
Uncaught (in promise) Error: Style is not done loading.
    at ie._checkLoaded (style.ts:374:19)
    at ie.addLayer (style.ts:652:14)
    at Map.addLayer (map.ts:1973:20)
    at (index):90:13
```

## なぜエラーがおきているのかの予想
非同期処理がうまく行っていないのかもと予想。非同期処理とは何なのかをまずは理解する必要あり

## 参考になりそうな資料
https://teratail.com/questions/141224

https://qiita.com/cheez921/items/41b744e4e002b966391a

**Comment by ShogoHirasawa** [comment]
## 非同期処理の理解ができていなかった。
非同期処理の構造を理解できていなかったためのエラーだった。コードを書き直したところ以下のような表示になった。
<img width="1296" alt="スクリーンショット 2022-06-14 23 07 24" src="https://user-images.githubusercontent.com/29940264/173597476-73003af3-b91d-45c1-b9a1-d1858eaabcb3.png">

openmaptilesの提供するフォントから選ばなきゃいけないっぽい。
以下を参考にすること
https://github.com/openmaptiles/fonts

**Comment by ShogoHirasawa** [comment]
## フォント変更
フォントをOpen Sans Regularに変更したら無事にフェッチできた
<img width="1132" alt="スクリーンショット 2022-06-14 23 08 43" src="https://user-images.githubusercontent.com/29940264/173597971-548ba6d8-a3de-45be-a311-dfe892b69dce.png">

**Comment by ShogoHirasawa** [comment]
## フォントエラーの詳細
[MapLibre GL JS Style Specification](https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#layout-symbol-text-font)によると、テキストフォントは設定しなければ自動的にOpen Sans Regular,Arial Unicode MS Regularになる仕様になっている。
<img width="723" alt="スクリーンショット 2022-06-14 23 36 18" src="https://user-images.githubusercontent.com/29940264/173604329-0ee4b9f8-407a-497b-b45d-1f241e9ae65f.png">

MapLibre GL JS が用意しているstyle.jsonを使えば問題ないが、今回の場合は独自でstyle.jsonを作っている。今回使用しているstyle.jsonの中身を見るとフォントはopenmaptilesから取ってきていることがわかった。
style.jsonに以下の記述がある。
```
 "glyphs": "https://fonts.openmaptiles.org/{fontstack}/{range}.pbf",
```
以下のフォントファミリーからフォントを選んであげることで、無事解決した。
<img width="834" alt="スクリーンショット 2022-06-14 23 40 56" src="https://user-images.githubusercontent.com/29940264/173605544-39ea7ffb-53de-46e6-8193-076ac8ad5a43.png">
